language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 19.3
  - 20.3
  - 21.3
env:
  - STRICT=true
  - STRICT=false
matrix:
  exclude:
    - elixir: 1.4
      env: STRICT=true
    - elixir: 1.5
      env: STRICT=true
    - elixir: 1.6
      env: STRICT=true
    - elixir: 1.7
      env: STRICT=true
    - elixir: 1.8
      env: STRICT=true
    - elixir: 1.9
      env: STRICT=false
    - elixir: 1.4
      otp_release: 21.3
    - elixir: 1.5
      otp_release: 21.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 19.3
script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi
